### ISSUE TITLE
Point a dependency at a specific commit

### ISSUE THREAD

**Issue by d2fn** [d2fn/gopack#3]
This is useful in the event a library maintainer has not supplied a tag or branch and you dont feel like forking just to point at a stable copy of their code.

**Comment by jnunemaker** [comment]
Yep, definitely handy. Bundler has pretty good options for git repos. They support ref, branch, and tag. To stay generic, commit is probably better name than ref.

**Comment by d2fn** [comment]
fixed in latest commit
